slow_scan: slow_scan.cu
	nvcc -Werror all-warnings -lcurand -O2 -o slow_scan slow_scan.cu
fast_scan: fast_scan.cu
	nvcc -Werror all-warnings -lcurand -O2 -o fast_scan fast_scan.cu
optimized_scan: optimized_scan.cu
	nvcc -Werror all-warnings -lcurand -O2 -o optimized_scan optimized_scan.cu
